import json
import os
from .ci import *  # pylint: disable=wildcard-import,unused-wildcard-import

ALLOWED_HOSTS: list[str] = [os.environ["DJANGO_ALLOWED_HOSTS"]]

OIDC_RP_CLIENT_ID = os.environ["OIDC_RP_CLIENT_ID"]
OIDC_RP_CLIENT_SECRET = os.environ["OIDC_RP_CLIENT_SECRET"]

KEYCLOAK_ADMIN_CLIENT_ID = os.environ["KEYCLOAK_ADMIN_CLIENT_ID"]
KEYCLOAK_ADMIN_CLIENT_SECRET = os.environ["KEYCLOAK_ADMIN_CLIENT_SECRET"]
KEYCLOAK_SERVER = os.environ["KEYCLOAK_SERVER"]

APIARY_TOKEN = os.environ["APIARY_TOKEN"]

RAMP_CLIENT_ID = os.environ["RAMP_CLIENT_ID"]
RAMP_CLIENT_SECRET = os.environ["RAMP_CLIENT_SECRET"]

GOOGLE_SERVICE_ACCOUNT_CREDENTIALS = json.loads(os.environ["GOOGLE_SERVICE_ACCOUNT_CREDENTIALS"])
GOOGLE_SUBJECT = os.environ["GOOGLE_SUBJECT"]
