# Generated by Django 5.1.7 on 2025-06-08 16:00
# pylint: skip-file
# mypy: ignore-errors

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "people"},
        ),
        migrations.AddField(
            model_name="person",
            name="hubspot_user_id",
            field=models.IntegerField(
                blank=True, null=True, unique=True, verbose_name="HubSpot user ID"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="google_workspace_user_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name="Google Workspace user ID",
            ),
        ),
    ]
