# Generated by Django 5.1.7 on 2025-06-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("org", "0002_alter_person_options_person_hubspot_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="If this person has a one-off title or a title shared with multiple people, you can set it here instead of using a position. If this person is in a position, the position title will take precedence.",
                max_length=100,
                null=True,
                verbose_name="Short title",
            ),
        ),
    ]
